### PR TITLE
DM-34254: Update piff psf kernelSize

### PR DESCRIPTION
**Pull request by parejkoj**

### CODE REVIEW

**Comment by kfindeisen** [comment]
I do not understand this PR. Why would this change be specific to the COSMOS dataset, or even `ap_verify`?

**Comment by parejkoj** [comment]
We need kernelSize=25 for the fakes, and the problem in the jira ticket was reported on this dataset. I made the change here so we could test it, and because changing it more broadly (e.g. making it the piff default) would impact DRP, who would want to more thoroughly test it.

**Comment by ebellm** [comment]
As we discussed in the weekly pipelines meeting, we should make this change at the ap_pipe level rather than in the individual CI datasets.

**Review by ebellm — CHANGES_REQUESTED** [review]
Make these defaults in ap_pipe instead.

**Pull request closed without merging**
